name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v2
  
        - name: Set up Conda
          uses: conda-incubator/setup-miniconda@v2
          with:
            auto-activate-base: false
  
        - name: Create Conda environment
          run: conda env create -f environment.yml
  
        - name: Initialize Conda
          shell: bash -l {0}
          run: conda init bash
  
        - name: Run tests with coverage report
          shell: bash -l {0}
          run: |
            conda activate SAO
            pytest tests/ --cov=aos --cov-report=term --cov-report=html

        - name: Upload Coverage Report
          if: always()
          uses: actions/upload-artifact@v2
          with:
            name: coverage-report
            path: htmlcov/

#pytest tests/ --cov=aos --cov-report=term --cov-report=html
#pytest --cov=your_package_name tests/test_your_module.py
