name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v2
  
        - name: Set up Conda
          uses: conda-incubator/setup-miniconda@v2
          with:
            auto-activate-base: false
  
        - name: Create Conda environment
          run: conda env create -f environment.yml
  
        - name: Initialize Conda
          shell: bash -l {0}
          run: conda init bash
  
        - name: Activate Conda environment and run tests
          shell: bash -l {0}
          run: |
            conda activate SAO
            python ./tests/t1_print.py



